version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: apollo_prisma_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apollo_prisma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Node.js API
  api:
    build: .
    container_name: apollo_prisma_api
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/apollo_prisma_db?schema=public"
      PORT: 4000
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: